# print(str(99), type(str(99)))
# print(str(0), type(str(0)))
# print(str(-56), type(str(-56)))
# print(str(5.5), type(str(5.5)))
# print(str(0.0), type(str(0.0)))
# print(str(-17.9), type(str(-17.9)))
# print(str('OK'), type(str('OK')))
# print(str('   '), type(str('   ')))
# print(str('0'), type(str('0')))
# print(str(''), type(str('')))
# print(str(True), type(str(True)))
# print(str(False), type(str(False)))
#
#
# print(int(99), type(int(99)))
# print(int(0), type(int(0)))
# print(int(-56), type(int(-56)))
# print(int(5.5), type(int(5.5)))
# print(int(0.0), type(int(0.0)))
# print(int(-17.9), type(int(-17.9)))
# print(int('OK'), type(int('OK')))
# print(int('   '), type(int('   ')))
# print(int('0'), type(int('0')))
# print(int(0.8), type(int(0.8)))
# print(int(''), type(int('')))
# print(int(True), type(int(True)))
# print(int(False), type(int(False)))
#
#
# print(float(99), type(float(99)))
# print(float(0), type(float(0)))
# print(float(-56), type(float(-56)))
# print(float(5.5), type(float(5.5)))
# print(float(0.0), type(float(0.0)))
# print(float(-17.9), type(float(-17.9)))
# print(float('OK'), type(float('OK')))
# print(float('   '), type(float('   ')))
# print(float('0'), type(float('0')))
# print(float('0.8'), type(float('0.8')))
# print(float(''), type(float('')))
# print(float(True), type(float(True)))
# print(float(False), type(float(False)))
#
#
# print(bool(99), type(bool(99)))
# print(bool(0), type(bool(0)))
# print(bool(-56), type(bool(-56)))
# print(bool(5.5), type(bool(5.5)))
# print(bool(0.0), type(bool(0.0)))
# print(bool(-17.9), type(bool(-17.9)))
# print(bool('OK'), type(bool('OK')))
# print(bool('   '), type(bool('   ')))
# print(bool('0'), type(bool('0')))
print(bool(''), type(bool('')))
# print(bool(True), type(bool(True)))
print(bool(False), type(bool(False)))