from tkinter import *
from tkinter.ttk import *

root = Tk()
root.title('Calculator for cat')
Label(text="Товар").grid(column=0, row=0)
Label(text="Qty,pc").grid(column=1, row=0)
Label(text="Price,pc").grid(column=2, row=0)
Label(text="Qty days").grid(column=3, row=0)
Label(text="Total Price").grid(column=5, row=0)
entry_11 = Entry()
entry_11.grid(column=0, row=1)
entry_12 = Entry()
entry_12.grid(column=1, row=1)
entry_13 = Entry()
entry_13.grid(column=2, row=1)
entry_14 = Entry()
entry_14.grid(column=3, row=1)
entry_15 = Entry()
entry_15.grid(column=5, row=1)
button_1 = Button(text="=")
button_1.grid(column=4, row=1)

entry_21 = Entry()
entry_21.grid(column=0, row=2)
entry_22 = Entry()
entry_22.grid(column=1, row=2)
entry_23 = Entry()
entry_23.grid(column=2, row=2)
entry_24 = Entry()
entry_24.grid(column=3, row=2)
entry_25 = Entry()
entry_25.grid(column=5, row=2)
button_2 = Button(text="=")
button_2.grid(column=4, row=2)

entry_31 = Entry()
entry_31.grid(column=0, row=3)
entry_32 = Entry()
entry_32.grid(column=1, row=3)
entry_33 = Entry()
entry_33.grid(column=2, row=3)
entry_34 = Entry()
entry_34.grid(column=3, row=3)
entry_35 = Entry()
entry_35.grid(column=5, row=3)
button_2 = Button(text="=")
button_2.grid(column=4, row=3)

Label(text="Всего затраты за год:", justify=RIGHT).grid(column=0, row=4, columnspan=4)
button_6 = Button(text="=")
button_6.grid(column=4, row=4)
entry_for_year = Entry()
entry_for_year.grid(column=5, row=4)

Label(text="Period, years:", justify=RIGHT).grid(column=0, row=5, columnspan=4)
# button_6 = Button(text="=")
# button_6.grid(column=4, row=4)
entry_for_year = Entry()
entry_for_year.grid(column=5, row=5)

Label(text="Total cost for whole period:", justify=RIGHT).grid(column=0, row=6, columnspan=4)
button_6 = Button(text="=")
button_6.grid(column=4, row=6)
entry_for_year = Entry()
entry_for_year.grid(column=5, row=6)
root.mainloop()